@startuml
class Ticket {
  - ticketNumber : int
  - seat : Seat
  - userId : int
  - movie : Movie
  - theater : Theater
  - showtime : Showtime
   Operation1() : 
   Operation2() : 
   toString(: UnknownType) : 
}
class Class1 {
   Attribute1 : 
}
class Movie {
  - name : String
  - theaters : ArrayList<Theater>
}
class Theater {
  - location : String
  - showtime : ArrayList<Showtime>
}
class Room {
  - roomNumber : int
  - seats : ArrayList<Seat>
}
class Seat {
  - seatNumber : int
  - isAvailable : boolean
   changeAvailability(: UnknownType) : 
}
class Showtime {
  - startTime : String
  - seats : ArrayList<Seats>
  - roomNumber : int
}
class BookingController {
  - tickets : ArrayList<Tickets>
  - movies : ArrayList<Movies>
   getAllMovies(: UnknownType) : 
   getAllTheaters(: UnknownType) : 
   getAllShowtimes(: UnknownType) : 
   getAllSeats(: UnknownType) : 
   findTicket(: Ticket, m: Movie, t: Theater, s: Showtime, st: Seat) : 
   bookTicket(t: Ticket, u: UnknownType, : UnknownType) : 
   findTicket(ticketNumber: UnknownType, : Ticket) : 
}
@enduml